[package]
name = "ray_tracing_in_one_weekend"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "raytracer"
path = "src/main.rs"

[dependencies]
rand = "0.9.1"
rand_chacha = "0.9.0"
rayon = "1.10.0"

